@startuml casos_uso
left to right direction
actor Cliente
actor Taquilla
rectangle "Sistema de Reservas" {
 usecase "Realizar Reserva"
 usecase "Cancelar Reserva"
 usecase "Registrar Ingreso"
 usecase "Reservar Sala"
}
Cliente --> "Realizar Reserva"
Cliente --> "Cancelar Reserva"
Taquilla --> "Registrar Ingreso"
Cliente --> "Reservar Sala"
@enduml